version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vscode
      POSTGRES_PASSWORD: vscode
      POSTGRES_DB: myblog
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://vscode:vscode@db:5432/myblog
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    # networks:
      # - mynetwork      

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    # networks:
      # - mynetwork

# networks:
#   mynetwork:
#     driver: bridge
volumes:
  db_data:
